### ISSUE TITLE
QC - зробити так, щоб напруга не збільшувалася неконтрольовано при збільшенні навантаження

### ISSUE THREAD

**Issue by trlumph** [trlumph/SmartUsbTester#6]

**Comment by serhii-matsyshyn** [comment]
Проблема трапляється лише з певними блоками живлення при некоректній початковій ініціалізації QC. Максимум що можна зробити у такому випадку - порівнювати змінну "очікувана напруга" з реальною у board_protection, якщо відхилення сильне - відключити навантаження, і попередити користувача про необхідність повторної ініціалізації/повторно ініціалізувати блок живлення.

**Comment by trlumph** [comment]
You can avoid that issue by not opening QC menu with the selected QC device. Then, the QC power source works as a regular one, therefore not jumping from one voltage level to another
